//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabAD_Katas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"33222234414453402D223E7F5B540F50261D22304B5551402B0C14715F434145286323305F55571A27223D644251515F2139702C5B4A5709707D696909454151366D393B0F4051442D3E212A5B496D6715011C3055595C6B76762028560D440D2E2A663054095A5A7F29312B5310415B313F333A0F5450643622293A51445D7500633D2C41415E1A37223D3A571E515B2976203A40435B47306D233A5145405D303470365C565D09022C3C2C570B5B5A2D39393E5E105155302C3C30550D5656143F3F265753465B05096B0B404541401728222957427151363939395B5353402170042D4755")]
        public string CadenaConexion {
            get {
                return ((string)(this["CadenaConexion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202F002D5D4957573022111B1C5D414735217E2C5D5D57516A2E3F32")]
        public string Servidor {
            get {
                return ((string)(this["Servidor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202F002D5D4957573022111B")]
        public string BaseDatos {
            get {
                return ((string)(this["BaseDatos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("342E20364141475D3D12030E7E7C5D532D230F6D")]
        public string Usuario {
            get {
                return ((string)(this["Usuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32743A38045F540D2C23")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
    }
}
